"""Add final_bills table

Revision ID: 05a5840bf1b5
Revises: 776da4a68c13
Create Date: 2026-07-04 16:13:25.779232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05a5840bf1b5'
down_revision: Union[str, None] = '776da4a68c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('final_bills',
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('bill_number', sa.String(length=50), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('catalog_item_id', sa.Uuid(), nullable=False),
    sa.Column('catalog_item_name', sa.String(length=200), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('advance_paid', sa.Integer(), nullable=False),
    sa.Column('balance_paid', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_index(op.f('ix_final_bills_bill_number'), 'final_bills', ['bill_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_final_bills_bill_number'), table_name='final_bills')
    op.drop_table('final_bills')
    # ### end Alembic commands ###
