"""Add BillingDocumentModel

Revision ID: 412149a5e262
Revises: 43c0340054d3
Create Date: 2026-07-04 18:08:44.969309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '412149a5e262'
down_revision: Union[str, None] = '43c0340054d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_documents',
    sa.Column('document_type', sa.Enum('BOOKING_RECEIPT', 'FINAL_BILL', name='billingdocumenttype'), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('generated_date', sa.String(length=20), nullable=False),
    sa.Column('generated_time', sa.String(length=20), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=True),
    sa.Column('document_path', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_documents_document_number'), 'billing_documents', ['document_number'], unique=True)
    op.add_column('booking_receipts', sa.Column('document_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'booking_receipts', 'billing_documents', ['document_id'], ['id'])
    op.add_column('final_bills', sa.Column('document_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'final_bills', 'billing_documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'final_bills', type_='foreignkey')
    op.drop_column('final_bills', 'document_id')
    op.drop_constraint(None, 'booking_receipts', type_='foreignkey')
    op.drop_column('booking_receipts', 'document_id')
    op.drop_index(op.f('ix_billing_documents_document_number'), table_name='billing_documents')
    op.drop_table('billing_documents')
    # ### end Alembic commands ###
