"""add_goods_receiving_model

Revision ID: 56b112546377
Revises: 833adda162fa
Create Date: 2026-07-05 18:12:07.693622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56b112546377'
down_revision: Union[str, None] = '833adda162fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods_receipts',
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipts_po_id'), 'goods_receipts', ['po_id'], unique=False)
    op.create_index(op.f('ix_goods_receipts_receipt_number'), 'goods_receipts', ['receipt_number'], unique=True)
    op.create_index(op.f('ix_goods_receipts_supplier_id'), 'goods_receipts', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_goods_receipts_warehouse_id'), 'goods_receipts', ['warehouse_id'], unique=False)
    op.create_table('goods_receipt_items',
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('po_item_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('ordered_quantity', sa.Integer(), nullable=False),
    sa.Column('received_quantity', sa.Integer(), nullable=False),
    sa.Column('accepted_quantity', sa.Integer(), nullable=False),
    sa.Column('line_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['po_item_id'], ['purchase_order_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['goods_receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipt_items_po_item_id'), 'goods_receipt_items', ['po_item_id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_items_product_id'), 'goods_receipt_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_items_receipt_id'), 'goods_receipt_items', ['receipt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goods_receipt_items_receipt_id'), table_name='goods_receipt_items')
    op.drop_index(op.f('ix_goods_receipt_items_product_id'), table_name='goods_receipt_items')
    op.drop_index(op.f('ix_goods_receipt_items_po_item_id'), table_name='goods_receipt_items')
    op.drop_table('goods_receipt_items')
    op.drop_index(op.f('ix_goods_receipts_warehouse_id'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_supplier_id'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_receipt_number'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_po_id'), table_name='goods_receipts')
    op.drop_table('goods_receipts')
    # ### end Alembic commands ###
