"""Update AppointmentModel fields

Revision ID: 776da4a68c13
Revises: 892e9c61f18d
Create Date: 2026-07-04 04:56:14.335011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776da4a68c13'
down_revision: Union[str, None] = '892e9c61f18d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('patient_id', sa.Uuid(), nullable=True))
    op.add_column('appointments', sa.Column('catalog_item_id', sa.Uuid(), nullable=True))
    op.add_column('appointments', sa.Column('receipt_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'receipt_number')
    op.drop_column('appointments', 'catalog_item_id')
    op.drop_column('appointments', 'patient_id')
    # ### end Alembic commands ###
