"""remove_unique_payment_id_receipt

Revision ID: 866f963a17a7
Revises: eff1420a55eb
Create Date: 2026-07-04 19:49:59.401813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '866f963a17a7'
down_revision: Union[str, None] = 'eff1420a55eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('booking_receipts_payment_id_key'), 'booking_receipts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('booking_receipts_payment_id_key'), 'booking_receipts', ['payment_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
