"""Add Billing Models

Revision ID: 892e9c61f18d
Revises: 37a49d764cc7
Create Date: 2026-07-04 04:44:05.703676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '892e9c61f18d'
down_revision: Union[str, None] = '37a49d764cc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.Enum('ADVANCE', 'FULL', name='paymenttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('transaction_reference', sa.String(length=255), nullable=True),
    sa.Column('is_non_refundable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_receipts',
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('catalog_item_id', sa.Uuid(), nullable=False),
    sa.Column('catalog_item_name', sa.String(length=200), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('advance_paid', sa.Integer(), nullable=False),
    sa.Column('remaining_amount', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_index(op.f('ix_booking_receipts_receipt_number'), 'booking_receipts', ['receipt_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_receipts_receipt_number'), table_name='booking_receipts')
    op.drop_table('booking_receipts')
    op.drop_table('payments')
    # ### end Alembic commands ###
