"""add_rebooking_lineage

Revision ID: eff1420a55eb
Revises: eee5e2f5ec1f
Create Date: 2026-07-04 19:40:02.340918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eff1420a55eb'
down_revision: Union[str, None] = 'eee5e2f5ec1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('rebooked_from_id', sa.Uuid(), nullable=True))
    op.add_column('appointments', sa.Column('rebooked_to_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'rebooked_to_id')
    op.drop_column('appointments', 'rebooked_from_id')
    # ### end Alembic commands ###
